// supabase-service.js
// Template / comments for future Supabase integration.
// DO NOT include keys in client repo. Example usage (commented):
/*
import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = 'https://your.supabase.url';
const SUPABASE_KEY = 'public-or-service-key';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// expected tables: admins, clientes, assinaturas, planos, servidores, apps, pontos_de_acesso, atividades
// fields generated by DB: id, data_de_criacao, data_de_vencimento
// Example query to fetch clients with active subscription:
const { data, error } = await supabase
  .from('clientes')
  .select(`
    id,nome,telefone,plano,
    assinaturas ( id, data_de_vencimento, telas ),
    planos ( id, nome, validadeEmMeses )
  `);
*/
